### ISSUE TITLE
IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by gigzz15** [rcarmo/imapbackup#10]
We encounter some problems regarding with I/O and this is the output:

`File INBOX.ACCOUNTS.mboxTraceback (most recent call last):
File "/usr/local/bin/imapbackup", line 749, in <module>
    main()
  File "/usr/local/bin/imapbackup", line 655, in main
    config['overwrite'], config['nospinner'])
  File "/usr/local/bin/imapbackup", line 225, in scan_file
    for message in mailbox.PortableUnixMailbox(mbox):
  File "/usr/local/lib/python2.7/mailbox.py", line 2072, in next
    self._search_end()
  File "/usr/local/lib/python2.7/mailbox.py", line 2095, in _search_end
    line = self.fp.readline()
IOError: [Errno 5] Input/output error`

it might get a workaround by using `>/dev/null 2>&1` at the end of the command line. Might as well update the script

**Comment by rcarmo** [comment]
This is erroring inside a readline() call in the Python standard library, not the script itself. IO errors of this kind are usually due to actual media issues or network issues if you’re using a network storage volume,

**Comment by gigzz15** [comment]
it seems that our network is having troubles. I extend the timeout to 300 for that to download the files. This will set to close, thank you!
