### ISSUE TITLE
instalacion?

### ISSUE THREAD

**Issue by killmasta93** [rcarmo/imapbackup#14]
Hi,
I was wondering if this could be applied to backup zimbra mailboxes?
to another ext4 or NTFS device?
Thank you

**Comment by rcarmo** [comment]
I honestly have no idea. I suppose Zimbra has IMAP? the kind of file system in use is not relevant at all.

**Comment by killmasta93** [comment]
thanks for the reply, correct zimbra uses IMAP but the idea is to backup the mailboxes my question is the the place where i store the backup is needed another IMAP server or it can store in mbox format or CUR? 

Thank you

**Comment by rcarmo** [comment]
That is all explained in the README.

**Comment by killmasta93** [comment]
thanks really nice script, working flawless quick question, possible a restore option back to the server?
