### ISSUE TITLE
Location saving?

### ISSUE THREAD

**Issue by farzadha2** [rcarmo/imapbackup#15]
Currently running the script saves the mbox files in the current directory.

`
NOTE: mbox files are created in the current working directory.
`
So i thought i would copy the script in different folder to backup a few emails and created a bash script but even though it saves in the root directory
```

python /media/usb/emailbak2/imapbackup.py --thunderbird -s mail.mydomain.com -u test@mydomain.com -p mypass -e 

python /media/usb/emailbak3/imapbackup.py --thunderbird -s mail.mydomain.com -u test@mydomain.com -p mypass -e 
```

Not sure if possible to tell the imapbackup.py to save in another directory? 

Thanks

**Comment by C-Duv** [comment]
"Current working directory" is not "where the executable is".
"Current working directory" is what `pwd` command prints.

To store backup at various places move into that directory before executing the command:
```Shell
cd /media/usb/emailbak2/
python /path/to/imapbackup.py --thunderbird -s mail.mydomain.com -u test@mydomain.com -p mypass -e

cd /media/usb/emailbak3/
python /path/to/imapbackup.py --thunderbird -s mail.mydomain.com -u test@mydomain.com -p mypass -e
```

Having a CLI option to define output directory would be great ;)

**Comment by farzadha2** [comment]
thanks for the reply, that did the trick yeah i wished be an option to do mass backing up with CLI option with directory
