### ISSUE TITLE
exclude trash folder?

### ISSUE THREAD

**Issue by killmasta93** [rcarmo/imapbackup#16]
Hi
I was wondering if its possible to exclude the trash folder?
I see the option -f but this option would be inbox and sent but if someone adds a folder outside of inbox it wont backup

Thank you

**Comment by killmasta93** [comment]
thanks for the reply.
so what would be the command to exclude the Trash?
I checked the help command but didnt find the exclude option
I think the trash folder i not in the Inbox.Trash as im currently running Zimbra
so it should be just Trash if i understood correctly 

this is the current command im running

`python imapbackup.py --thunderbird -s mail.mydomain.com -u administracion@mydomain.com.com -p mypassowrd  -e`

**Comment by rcarmo** [comment]
You'd have to enumerate the folders you _want_ backed up. Currently there is no way to exclude a folder (this was originally designed for mailbox migrations, and original priority was to backup all or a specific subset, not exclude some things).
