### ISSUE TITLE
imapbackup.py doesn't run on Fedora 32 (Python 3.8.3)

### ISSUE THREAD

**Issue by d-graef** [rcarmo/imapbackup#18]
On Fedora Linux version: Fedora release 32 (Thirty Two)
I get the follwoing error:

/usr/bin/env: „python -u“: Datei oder Verzeichnis nicht gefunden
/usr/bin/env: Verwenden Sie -[v]S, um Optionen in #!-Zeichen zu übergeben

replacing #!/usr/bin/env python -u

with

#!/usr/bin/env -S python -u

solves the problem.

But then I get a lot of errors regarding the print statement:

Python version is:

python --version
Python 3.8.3

  File ".../imap-backup/imapbackup.py", line 145
    print "Deleting", filename
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Deleting", filename)?

  File ".../imap-backup/imapbackup.py", line 163
    print "New messages: 0"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("New messages: 0")?

  File ".../imap-backup/imapbackup.py", line 206
    print ": %s total, %s for largest message" % (pretty_byte_count(total),
          ^
SyntaxError: invalid syntax

 File "/.../imap-backup/imapbackup.py", line 220
    print "File %s: not found" % filename
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("File %s: not found" % filename)?

  File "/..../imap-backup/imapbackup.py", line 245
    print "WARNING: Message #%d in %s" % (i, filename),
          ^
SyntaxError: invalid syntax

  File "/..../imap-backup/imapbackup.py", line 258
    print "WARNING: Message #%d in %s" % (i, filename),
          ^
SyntaxError: invalid syntax

  File "/..../imap-backup/imapbackup.py", line 266
    print ": %d messages" % (len(messages.keys()))
          ^
SyntaxError: invalid syntax

  File "/.../imap-backup/imapbackup.py", line 311
    print ":",
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(":", end=" ")?

  File "/..../imap-backup/imapbackup.py", line 314
    print "%d messages" % (len(messages.keys()))
          ^
SyntaxError: invalid syntax

  File "/.../imap-backup/imapbackup.py", line 415
    print ": %s folders" % (len(names))
          ^
SyntaxError: invalid syntax

  File "/.../imap-backup/imapbackup.py", line 422
    print "Usage: imapbackup [OPTIONS] -s HOST -u USERNAME [-p PASSWORD]"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Usage: imapbackup [OPTIONS] -s HOST -u USERNAME [-p PASSWORD]")?

  File "/..../imap-backup/imapbackup.py", line 584
    print "WARNING:", warning
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING:", warning)?

  File "/.../imap-backup/imapbackup.py", line 617
    print "Connecting to '%s' TCP port %d," % (
          ^
SyntaxError: invalid syntax

  File "/.../imap-backup/imapbackup.py", line 635
    print "Logging in as '%s'" % (config['user'])
          ^
SyntaxError: invalid syntax

  File "/.../imap-backup/imapbackup.py", line 636
    server.login(config['user'], config['pass']))
    ^
SyntaxError: invalid syntax

**Comment by d-graef** [comment]
I've no clue about Python, but I've fixed the syntax errors. When I run the script with Python3 I get the following errors.
With python2 (Python 2.7.18) the script is working.
Do you expect a pull request with a new file imapbackup3.py or imapbackup38.py?
I don't know if it is possible to keep one file compatible to run with python2.x and python 3.x.
I can povide a new file where only the syntax errors are fixed.

Connecting to 'imap.....de' TCP port 993, SSL
Logging in as '.....'
Finding Folders |Traceback (most recent call last):
  File "/.../imap-backup/imapbackup.py", line 672, in main
    names = get_names(server, config['compress'], config['thunderbird'],
  File "/.../imap-backup/imapbackup.py", line 388, in get_names
    delim = get_hierarchy_delimiter(server)
  File "/.../imap-backup/imapbackup.py", line 371, in get_hierarchy_delimiter
    typ, data = server.list('', '')
  File "/usr/lib64/python3.8/imaplib.py", line 590, in list
    typ, dat = self._simple_command(name, directory, pattern)
  File "/usr/lib64/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib64/python3.8/imaplib.py", line 1030, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: LIST command error: BAD [b'Error in IMAP command LIST: Invalid reference (0.001 + 0.000 secs).']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../imap-backup/imapbackup.py", line 788, in <module>
    main()
  File "/.../imap-backup/imapbackup.py", line 708, in main
    except (socket.error, e):
NameError: name 'e' is not defined

**Comment by rcarmo** [comment]
You are correct in that this needs to be a separate file for 3.8. I have not had the time to write one, but a pull request with a `3` or `38` suffix would be great.

**Comment by mhow2** [comment]
I had to add `-S` option in the env call from `imapbackup38.py` today. Otherwise I get:

```
/usr/bin/env: ‘python3 -u’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```
