### ISSUE TITLE
Overwrite prevents downloading anything

### ISSUE THREAD

**Issue by andrewbaxter** [rcarmo/imapbackup#2]
I think.  I run this and it scans folders for a while then quits without writing anything.  I noticed folders aren't created either.

I ran with `-b -y -s HOST -u USER -p PASS`.  Running with `-a -s HOST -u USER -p PASS` appears to work (so far, just started it).

This line in download_messages returns if 'overwrite' is set: https://github.com/rcarmo/imapbackup/blob/master/imapbackup.py#L108 .  Not sure if that's relevant.

**Comment by andrewbaxter** [comment]
Here's the logs:
```
WARNING: Existing mbox files will be overwritten!
Connecting to 'x' TCP port 143
Logging in as 'x'
Finding Folders: 12 folders
Folder Deleted Messages: 0 messages
Folder Drafts: 25 messages
Folder INBOX: 1862 messages
Folder INBOX.Trash: 0 messages
Folder Sent: 474 messages
Folder Sent Items: 76 messages
Folder Sent Messages: 44 messages
Folder Spam: 0 messages
Folder Trash: 0 messages
Folder Trash/x: 48 messages
Folder x: 158 messages
Folder x: 238 messages
Disconnecting
```

**Comment by jwagnerhki** [comment]
It is because in main(), around lines

        new_messages = {}
        for msg_id in fol_messages:
          if msg_id not in fil_messages:
            new_messages[msg_id] = fol_messages[msg_id]

the

        for msg_id in fol_messages:

should be

        for msg_id in fol_messages.keys():

Then the incremental update works. I'll try to join this project and submit a fix. Since overall imapbackup.py is very nice and simple and does its job; i just backed up 1.6GB of mailbox folders for migrating.

**Comment by rcarmo** [comment]
Ah... that might have to do with ancient Python semantics, and little tweaks made (or not made) over the years (remember this had to run in ancient 2.x versions).

I'll push a change for that when I get to a real computer.
