### ISSUE TITLE
Can't run on python 3.9.5 windows

### ISSUE THREAD

**Issue by leaumar** [rcarmo/imapbackup#23]
I have no experience with python so perhaps I'm making a rookie mistake, but since the project says it has 0 dependencies I wouldn't know what it could be.

I think the following output from my terminal says it all:
```
PS D:\Downloads\Edge\imapbackup-master> python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

PS D:\Downloads\Edge\imapbackup-master> python imapbackup38.py
Traceback (most recent call last):
  File "D:\Downloads\Edge\imapbackup-master\imapbackup38.py", line 58, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'
```

The same thing happened with python 3.8.5. Any tips, please?

**Comment by rcarmo** [comment]
I'll need to check what Python for Windows comes with these days, and what happened to `six`. The Python 3.8 version was supplied by @mmachicao, so tagging him for follow-up as he might not be aware that he introduced that dependency and it needs to be taken out.

**Comment by mmachicao** [comment]
Hi

Nice to hear, the Python 3 version is actually being used.

Not aware, that I added any non-standard dependency.

Perhaps a minor fix to imapbackup38 to support 3.8 upwards.

Alternatively, add imapbackup39 to support 3.9 upwards

Anyway update the README.md

Marco

**Comment by mmachicao** [comment]
Interesting...

Only one occurrence.

Conflict is here:

assert isinstance(value, string_types)

**Comment by mmachicao** [comment]
Dependency is removed and fix has been merged.

**Comment by leaumar** [comment]
Thanks, I gave it another go and it worked. Now I've run into what seems like a bug to me, perhaps protocol version differences? I'll log it as a separate ticket.

**Comment by rcarmo** [comment]
Thanks to both, I'll close this and check the other ticket.
