### ISSUE TITLE
mailbox.org: `Error in IMAP command LIST`

### ISSUE THREAD

**Issue by leaumar** [rcarmo/imapbackup#25]
Running `python imapbackup38.py -f INBOX --ssl -s imap.mailbox.org -u leaumar@mailbox.org` yields the following:

> Password:
> Connecting to 'imap.mailbox.org' TCP port 993, SSL
> Logging in as 'leaumar@mailbox.org'
> Finding Folders |ERROR: LIST command error: BAD [b'Error in IMAP command LIST: Invalid reference (0.001 + 0.000 secs).']

I'm sure the folder name is correct (screenshot), and the CLI help says the folders argument is a comma-separated list, so I'm not sure what I could be doing wrong if this isn't a bug.

![image](https://user-images.githubusercontent.com/3950300/118268491-bbf2c400-b4bd-11eb-9ded-c051fe3e29d7.png)

**Comment by leaumar** [comment]
FYI, doing the same thing with https://github.com/rtucker/imap2maildir works (`python imap2maildir.py -u leaumar@mailbox.org -d ./2021-05-14.mbox -H imap.mailbox.org -P 993 -r INBOX --create --ssl -t mbox`), so there might be a key difference in the implementations

**Comment by rcarmo** [comment]
Hmm. @mmachicao, can you reprodyce this? I will try on a Mac when I have the time.

**Comment by mmachicao** [comment]
@rcarmo , @leaumar :  Cannot reproduce on Win10 WSL2 with my email provider.

Output suggest, error happens when resolving the hierarchy delimiter.

Here:

def get_hierarchy_delimiter(server):
    """Queries the imapd for the hierarchy delimiter, eg. '.' in INBOX.Sent"""
    # see RFC 3501 page 39 paragraph 4
    typ, data = server.list('', '')

According to RFC3501 this is perfectly legal, maybe not supported by mailbox.org

Alternative:

In get_names: 
- Drop get_hierarchy_delimiter
- Read hierarchy delimiter when processing folders

....
    # parse each LIST, find folder name
    for row in data:
        row_str = str(row,'utf-8')
        lst = parse_list(row_str)
        delim = lst[1]    <<---- READ DELIMITER
        foldername = lst[2] 
...

**Comment by kobajagi** [comment]
For the record same issue happens with migadu.com. So I tried a patch from https://github.com/rcarmo/imapbackup/pull/27 and it indeed solves the issue (for migadu at least).

**Comment by leaumar** [comment]
Closing because fixed, thanks
