### ISSUE TITLE
Can't have space in `--folders` name?

### ISSUE THREAD

**Issue by leaumar** [rcarmo/imapbackup#28]
Output from my terminal:
```
D:\Projects\Windows Shell>python ..\imapbackup\imapbackup38.py -f "Archived,Elysia Park" --ssl -s imap.mailbox.org -u leaumar@mailbox.org -d mailbox.org
Password:
Connecting to 'imap.mailbox.org' TCP port 993, SSL
Logging in as 'leaumar@mailbox.org'
Finding Folders /(\HasNoChildren \UnMarked) "/" "Elysia Park"
(\HasNoChildren \UnMarked) "/" Archived
(\HasNoChildren \UnMarked) "/" Accounts
(\HasNoChildren \UnMarked) "/" Receipts
(\HasNoChildren \UnMarked \Junk) "/" Junk
(\HasNoChildren \UnMarked \Trash) "/" Trash
(\HasNoChildren \UnMarked \Drafts) "/" Drafts
(\HasNoChildren \UnMarked \Sent) "/" Sent
(\HasNoChildren) "/" INBOX
Finding Folders: 9 folders
Folder Elysia Park:
SELECT failed: [b"Mailbox doesn't exist: Elysia (0.001 + 0.000 secs)."]
Folder Archived:
8 messages
File Archived.mbox: 8 messages
New messages: 0
Disconnecting
```

(minor side note: a linebreak after "Finding Folders" would keep the folder listing nicely laid out)

As you can see there's a folder with a space in its name and it shows up verbatim in the listing, but the SELECT apparently can't handle it and truncates what comes after the space.

**Comment by DanielRuf** [comment]
Did you already try to encode the space like this?

`"Archived,Elysia\ Park"`

**Comment by leaumar** [comment]
Doing that makes it silently skip that folder for saving. It's still listed in "Finding folders", but no attempt is made to save its content.

**Comment by DanielRuf** [comment]
I probably stumbled upon the same issue but when I fetch all folders.

```
Folder INBOX/Email (Newsletter):
ERROR: EXAMINE command error: BAD [b'Error in IMAP command EXAMINE: Unknown FETCH modifier (0.001 + 0.000 secs).']
```

**Comment by DanielRuf** [comment]
As this is some sort of blocker for me, is there some easy fix @rcarmo that I can apply?

**Comment by DanielRuf** [comment]
I guess this is a bug with `imaplib`. I'll check if I find some information.

**Comment by DanielRuf** [comment]
@leaumar I have created a PR at https://github.com/rcarmo/imapbackup/pull/34

Maybe you can test it. Not sure if this fully resolves this issue (we will now also see the full folder name / path encapsulated in quotes which might be more helpful) or if we have to adjust `config['folders'] = value` (see also my remarks about possible arbitrary code execution, directory traversal and so on).

**Comment by DanielRuf** [comment]
This should be resolved now, https://github.com/rcarmo/imapbackup/pull/34 was merged yesterday.

**Comment by leaumar** [comment]
Thanks! I don't use it anymore in the meantime though. Probably best I leave closing this to someone else.
