### ISSUE TITLE
Maildir support?

### ISSUE THREAD

**Issue by dumblob** [rcarmo/imapbackup#38]
I wonder whether anyone thought about supporting maildir (in addition to mbox) to make the backup less susceptible to errors.

Thoughts?

**Comment by rcarmo** [comment]
I have. A `maildir` backup is essentially what you'd get if you used `mutt` and downloaded your entire folder tree, it's not really a backup format but just a set of individual message files.

**Comment by dumblob** [comment]
That's an interesting idea. First link when googling it: http://jeromebelleman.gitlab.io/posts/devops/mailbkp/ . Sounds viable though I still need to consider all the pros & cons (especially considering my backup shall be executable with minor changes on Windows as well as on Linux machines).

**Comment by dumblob** [comment]
That idea kind of works but it proved anyway more complicated to set up than I'd require. So the python way would still be preferred. If there are no plans for maildir, then feel free to close this as 'wontfix'.
