### ISSUE TITLE
Any support for IMAP flags?

### ISSUE THREAD

**Issue by dumblob** [rcarmo/imapbackup#39]
I'm new to imapbackup and wonder whether there is any support for IMAP flags? If not, do they get trashed or ignored or somehow influence the resulting mbox database?

**Comment by rcarmo** [comment]
Flags are not saved, there is no relationship between IMAP status and the actual RFC2822 message format and no agreed upon way to save them in `mbox`.

**Comment by dumblob** [comment]
That is true. Would you agree that flags are useful at least for manual exploration of the mbox file? I'd very much like to save them (in the end it's called "imap**backup**" :wink:).

**Comment by dumblob** [comment]
Just to clarify - for my use case only the read/unread state (i.e. "IMAP system flags") is important. Anything else is just nice-to-have.

**Comment by rcarmo** [comment]
Yes, but there is no standard way to store that, and the script does not restore messages either, so it’s a “wontfix” unless someone contributes code to do both.

**Comment by dumblob** [comment]
Ok, I understand. Feel free to close this issue if you don't consider it as a "planned feature without a deadline" :wink:.

**Comment by dumblob** [comment]
Let's close this as 'wontfix' for now.
